### ISSUE TITLE
Suggestion: Adding in different types of companions with mod compatibility 

### ISSUE THREAD

**Issue by DWX12** [Ladysnake/LightOrbs#2]
There are various mods out there that add content and interact when they detect other mods that are loaded. One mod that comes to mind is Spartan Shields with its collection of shields that are enabled if certain mods are present.

This is a neat mod that I can see adding companions from various mods such as wisps from Thaumcraft, fairies from Botania and Roots, mechanical ones from different tech mods, pixies from Ice and Fire, fire flies from Twilight Forest, etc.

A cool little atmospheric mod that can further tie together mod packs.

Thank you for making this and hope you gain inspiration from this suggestion.

**Comment by RiverLeviathan** [comment]
Very nice suggestion, thank you! I had in fact an idea similar to that, and since I really want to implement a ton of companion orbs to chose from, this might happen. However, I don't really play modded MC because of little free time I have to do so, so the cross compatibility I'll do will only be with mods I genuinely love and spend time on. But if you have any precise idea, please let me know and I'll look into it.
